# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aukcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[(b'Aukcija u toku', b'Aukcija u toku'), (b'Istekla aukcija, predmet prodat', b'Istekla aukcija, predmet prodat'), (b'Istekla aukcija, predmet nije prodat', b'Istekla aukcija, predmet nije prodat')], max_length=200, null=True)),
                ('korisnik', models.ManyToManyField(to='users.Korisnik')),
            ],
        ),
        migrations.DeleteModel(
            name='Oglas',
        ),
        migrations.AddField(
            model_name='predmet',
            name='korisnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Korisnik'),
        ),
        migrations.AddField(
            model_name='predmet',
            name='trajanje_aukcije',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='aukcija',
            name='predmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Predmet'),
        ),
    ]
