# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201014_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
