# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201014_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='pocetna_cena',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='trajanje_aukcije',
            field=models.DateTimeField(null=True),
        ),
    ]
