# Generated by Django 3.1.2 on 2020-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201014_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aukcija',
            name='status',
            field=models.CharField(choices=[('Aukcija u toku', 'Aukcija u toku'), ('Istekla aukcija, predmet prodat', 'Istekla aukcija, predmet prodat'), ('Istekla aukcija, predmet nije prodat', 'Istekla aukcija, predmet nije prodat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='kategorija',
            field=models.CharField(choices=[('Knjige', 'Knjige'), ('Oprema', 'Oprema'), ('Ostalo', 'Ostalo')], max_length=200, null=True),
        ),
    ]
