# Generated by Django 3.1.2 on 2020-10-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201015_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bider',
            old_name='ime',
            new_name='korisnik',
        ),
        migrations.RenameField(
            model_name='oglasivac',
            old_name='ime',
            new_name='korisnik',
        ),
    ]
