# Generated by Django 3.1.2 on 2020-10-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201015_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmet',
            name='bideri',
        ),
        migrations.AddField(
            model_name='predmet',
            name='bider',
            field=models.ManyToManyField(blank=True, to='users.Bider'),
        ),
        migrations.AlterField(
            model_name='bider',
            name='korisnik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.korisnik'),
        ),
        migrations.AlterField(
            model_name='oglasivac',
            name='korisnik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.korisnik'),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='opis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
