# Generated by Django 3.1.2 on 2020-10-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201015_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='bider',
            field=models.ManyToManyField(to='users.Bider'),
        ),
    ]
