# Generated by Django 3.1.2 on 2020-10-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201015_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
